// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dskmiajizazkcfyotibk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRza21pYWppemF6a2NmeW90aWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTk4MzMsImV4cCI6MjA2OTk5NTgzM30.rI5Q_ubx5FF-bXOg1LLM-DbI_ugbJFsZHnVOIEUVO7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});